name: Pipeline Limpio V2

on:
  schedule:
    - cron: '0 10 * * 1-5' # Se ejecuta automático de lunes a viernes
  workflow_dispatch: # Botón manual para forzar la ejecución

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar librerías
        run: pip install -r requirements.txt
        
      - name: Ejecutar motor de datos
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          CHILE_USER: ${{ secrets.CHILE_USER }}
          CHILE_PASS: ${{ secrets.CHILE_PASS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        run: python pipeline_v2.py
